// Code generated by protoc-gen-goten-client
// API: ProbeStatusService
// DO NOT EDIT!!!

package probe_status_client

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// proto imports
import ()

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = protoimpl.DescBuilder{}
	_ = context.Context(nil)
	_ = grpc.ClientConn{}
)

// make sure we're using proto imports
var ()

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProbeStatusServiceClient is the client API for ProbeStatusService.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProbeStatusServiceClient interface {
	ProbeStatus(ctx context.Context, in *ProbeStatusRequest, opts ...grpc.CallOption) (*ProbeStatusResponse, error)
}

type client struct {
	cc grpc.ClientConnInterface
}

func NewProbeStatusServiceClient(cc grpc.ClientConnInterface) ProbeStatusServiceClient {
	return &client{cc}
}

func (c *client) ProbeStatus(ctx context.Context, in *ProbeStatusRequest, opts ...grpc.CallOption) (*ProbeStatusResponse, error) {
	out := new(ProbeStatusResponse)
	err := c.cc.Invoke(ctx, "/ntt.watchdog.v1alpha.ProbeStatusService/ProbeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
