// Code generated by protoc-gen-goten-access
// Resource: ProbingTarget
// DO NOT EDIT!!!

package probing_target_access

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	gotenaccess "github.com/cloudwan/goten-sdk/runtime/access"
	"github.com/cloudwan/goten-sdk/runtime/api/watch_type"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"

	probing_target_client "github.com/cloudwan/watchdog-sdk/client/v1alpha2/probing_target"
	probing_target "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/probing_target"
)

var (
	_ = new(context.Context)
	_ = new(fmt.GoStringer)

	_ = new(grpc.ClientConnInterface)
	_ = codes.NotFound
	_ = status.Status{}

	_ = new(gotenaccess.Watcher)
	_ = watch_type.WatchType_STATEFUL
	_ = new(gotenresource.ListQuery)
)

type apiProbingTargetAccess struct {
	client probing_target_client.ProbingTargetServiceClient
}

func NewApiProbingTargetAccess(client probing_target_client.ProbingTargetServiceClient) probing_target.ProbingTargetAccess {
	return &apiProbingTargetAccess{client: client}
}

func (a *apiProbingTargetAccess) GetProbingTarget(ctx context.Context, query *probing_target.GetQuery) (*probing_target.ProbingTarget, error) {
	request := &probing_target_client.GetProbingTargetRequest{
		Name:      query.Reference,
		FieldMask: query.Mask,
	}
	res, err := a.client.GetProbingTarget(ctx, request)
	if err != nil {
		return nil, err
	}
	query.Reference.Resolve(res)
	return res, nil
}

func (a *apiProbingTargetAccess) BatchGetProbingTargets(ctx context.Context, refs []*probing_target.Reference, opts ...gotenresource.BatchGetOption) error {
	batchGetOpts := gotenresource.MakeBatchGetOptions(opts)
	request := &probing_target_client.BatchGetProbingTargetsRequest{
		Names: refs,
	}
	resp, err := a.client.BatchGetProbingTargets(ctx, request)
	if err != nil {
		return err
	}
	resultMap := make(map[probing_target.Name]*probing_target.ProbingTarget, len(refs))
	for _, resolvedRes := range resp.GetProbingTargets() {
		resultMap[*resolvedRes.GetName()] = resolvedRes
	}
	for _, ref := range refs {
		resolvedRes := resultMap[ref.Name]
		if resolvedRes != nil {
			ref.Resolve(resolvedRes)
		}
	}
	if batchGetOpts.MustResolveAll() && len(resp.GetMissing()) > 0 {
		return status.Errorf(codes.NotFound, "Number of references not found: %d", len(resp.GetMissing()))
	}
	return nil
}

func (a *apiProbingTargetAccess) QueryProbingTargets(ctx context.Context, query *probing_target.ListQuery) (*probing_target.QueryResultSnapshot, error) {
	request := &probing_target_client.ListProbingTargetsRequest{
		Filter:    query.Filter,
		FieldMask: query.Mask,
	}
	if query.Pager != nil {
		request.PageSize = int32(query.Pager.Limit)
		request.OrderBy = query.Pager.OrderBy
		request.PageToken = query.Pager.Cursor
	}
	resp, err := a.client.ListProbingTargets(ctx, request)
	if err != nil {
		return nil, err
	}
	return &probing_target.QueryResultSnapshot{
		ProbingTargets: resp.ProbingTargets,
		NextPageCursor: resp.NextPageToken,
		PrevPageCursor: resp.PrevPageToken,
	}, nil
}

func (a *apiProbingTargetAccess) SearchProbingTargets(ctx context.Context, query *probing_target.SearchQuery) (*probing_target.SearchQueryResultSnapshot, error) {
	request := &probing_target_client.SearchProbingTargetsRequest{
		Phrase:    query.Phrase,
		Filter:    query.Filter,
		FieldMask: query.Mask,
	}
	if query.Pager != nil {
		request.PageSize = int32(query.Pager.Limit)
		request.OrderBy = query.Pager.OrderBy
		request.PageToken = query.Pager.Cursor
	}
	resp, err := a.client.SearchProbingTargets(ctx, request)
	if err != nil {
		return nil, err
	}
	return &probing_target.SearchQueryResultSnapshot{
		QueryResultSnapshot: probing_target.QueryResultSnapshot{
			ProbingTargets: resp.ProbingTargets,
			NextPageCursor: resp.NextPageToken,
			PrevPageCursor: resp.PrevPageToken,
		},
		CurrentOffset:     resp.CurrentOffset,
		TotalResultsCount: resp.TotalResultsCount,
	}, nil
}

func (a *apiProbingTargetAccess) WatchProbingTarget(ctx context.Context, query *probing_target.GetQuery, observerCb func(*probing_target.ProbingTargetChange) error) error {
	request := &probing_target_client.WatchProbingTargetRequest{
		Name:      query.Reference,
		FieldMask: query.Mask,
	}
	changesStream, initErr := a.client.WatchProbingTarget(ctx, request)
	if initErr != nil {
		return initErr
	}
	for {
		resp, err := changesStream.Recv()
		if err != nil {
			return fmt.Errorf("watch recv error: %w", err)
		}
		change := resp.GetChange()
		if err := observerCb(change); err != nil {
			return err
		}
	}
}

func (a *apiProbingTargetAccess) WatchProbingTargets(ctx context.Context, query *probing_target.WatchQuery, observerCb func(*probing_target.QueryResultChange) error) error {
	request := &probing_target_client.WatchProbingTargetsRequest{
		Filter:       query.Filter,
		FieldMask:    query.Mask,
		MaxChunkSize: int32(query.ChunkSize),
		Type:         query.WatchType,
		ResumeToken:  query.ResumeToken,
	}
	if query.Pager != nil {
		request.OrderBy = query.Pager.OrderBy
		request.PageSize = int32(query.Pager.Limit)
		request.PageToken = query.Pager.Cursor
	}
	changesStream, initErr := a.client.WatchProbingTargets(ctx, request)
	if initErr != nil {
		return initErr
	}
	for {
		respChange, err := changesStream.Recv()
		if err != nil {
			return fmt.Errorf("watch recv error: %w", err)
		}
		changesWithPaging := &probing_target.QueryResultChange{
			Changes:      respChange.ProbingTargetChanges,
			IsCurrent:    respChange.IsCurrent,
			IsHardReset:  respChange.IsHardReset,
			IsSoftReset:  respChange.IsSoftReset,
			ResumeToken:  respChange.ResumeToken,
			SnapshotSize: respChange.SnapshotSize,
		}
		if respChange.PageTokenChange != nil {
			changesWithPaging.PrevPageCursor = respChange.PageTokenChange.PrevPageToken
			changesWithPaging.NextPageCursor = respChange.PageTokenChange.NextPageToken
		}
		if err := observerCb(changesWithPaging); err != nil {
			return err
		}
	}
}

func (a *apiProbingTargetAccess) SaveProbingTarget(ctx context.Context, res *probing_target.ProbingTarget, opts ...gotenresource.SaveOption) error {
	saveOpts := gotenresource.MakeSaveOptions(opts)
	previousRes := saveOpts.GetPreviousResource()

	if previousRes == nil && !saveOpts.OnlyUpdate() && !saveOpts.OnlyCreate() {
		var err error
		previousRes, err = a.GetProbingTarget(ctx, &probing_target.GetQuery{Reference: res.Name.AsReference()})
		if err != nil {
			if statusErr, ok := status.FromError(err); !ok || statusErr.Code() != codes.NotFound {
				return err
			}
		}
	}

	if saveOpts.OnlyUpdate() || previousRes != nil {
		updateRequest := &probing_target_client.UpdateProbingTargetRequest{
			ProbingTarget: res,
		}
		if updateMask := saveOpts.GetUpdateMask(); updateMask != nil {
			updateRequest.UpdateMask = updateMask.(*probing_target.ProbingTarget_FieldMask)
		}
		if mask, conditionalState := saveOpts.GetCAS(); mask != nil && conditionalState != nil {
			updateRequest.Cas = &probing_target_client.UpdateProbingTargetRequest_CAS{
				ConditionalState: conditionalState.(*probing_target.ProbingTarget),
				FieldMask:        mask.(*probing_target.ProbingTarget_FieldMask),
			}
		}
		_, err := a.client.UpdateProbingTarget(ctx, updateRequest)
		if err != nil {
			return err
		}
		return nil
	} else {
		createRequest := &probing_target_client.CreateProbingTargetRequest{
			ProbingTarget: res,
		}
		_, err := a.client.CreateProbingTarget(ctx, createRequest)
		if err != nil {
			return err
		}
		return nil
	}
}

func (a *apiProbingTargetAccess) DeleteProbingTarget(ctx context.Context, ref *probing_target.Reference, opts ...gotenresource.DeleteOption) error {
	request := &probing_target_client.DeleteProbingTargetRequest{
		Name: ref,
	}
	_, err := a.client.DeleteProbingTarget(ctx, request)
	return err
}

func init() {
	gotenaccess.GetRegistry().RegisterApiAccessConstructor(probing_target.GetDescriptor(), func(cc grpc.ClientConnInterface) gotenresource.Access {
		return probing_target.AsAnyCastAccess(NewApiProbingTargetAccess(probing_target_client.NewProbingTargetServiceClient(cc)))
	})
}
