// Code generated by protoc-gen-goten-access
// Resource: Probe
// DO NOT EDIT!!!

package probe_access

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	gotenaccess "github.com/cloudwan/goten-sdk/runtime/access"
	"github.com/cloudwan/goten-sdk/runtime/api/watch_type"
	gotenresource "github.com/cloudwan/goten-sdk/runtime/resource"

	probe_client "github.com/cloudwan/watchdog-sdk/client/v1alpha2/probe"
	probe "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/probe"
)

var (
	_ = new(context.Context)
	_ = new(fmt.GoStringer)

	_ = new(grpc.ClientConnInterface)
	_ = codes.NotFound
	_ = status.Status{}

	_ = new(gotenaccess.Watcher)
	_ = watch_type.WatchType_STATEFUL
	_ = new(gotenresource.ListQuery)
)

type apiProbeAccess struct {
	client probe_client.ProbeServiceClient
}

func NewApiProbeAccess(client probe_client.ProbeServiceClient) probe.ProbeAccess {
	return &apiProbeAccess{client: client}
}

func (a *apiProbeAccess) GetProbe(ctx context.Context, query *probe.GetQuery) (*probe.Probe, error) {
	request := &probe_client.GetProbeRequest{
		Name:      query.Reference,
		FieldMask: query.Mask,
	}
	res, err := a.client.GetProbe(ctx, request)
	if err != nil {
		return nil, err
	}
	query.Reference.Resolve(res)
	return res, nil
}

func (a *apiProbeAccess) BatchGetProbes(ctx context.Context, refs []*probe.Reference, opts ...gotenresource.BatchGetOption) error {
	batchGetOpts := gotenresource.MakeBatchGetOptions(opts)
	request := &probe_client.BatchGetProbesRequest{
		Names: refs,
	}
	fieldMask := batchGetOpts.GetFieldMask(probe.GetDescriptor())
	if fieldMask != nil {
		request.FieldMask = fieldMask.(*probe.Probe_FieldMask)
	}
	resp, err := a.client.BatchGetProbes(ctx, request)
	if err != nil {
		return err
	}
	resultMap := make(map[probe.Name]*probe.Probe, len(refs))
	for _, resolvedRes := range resp.GetProbes() {
		resultMap[*resolvedRes.GetName()] = resolvedRes
	}
	for _, ref := range refs {
		resolvedRes := resultMap[ref.Name]
		if resolvedRes != nil {
			ref.Resolve(resolvedRes)
		}
	}
	if batchGetOpts.MustResolveAll() && len(resp.GetMissing()) > 0 {
		return status.Errorf(codes.NotFound, "Number of references not found: %d", len(resp.GetMissing()))
	}
	return nil
}

func (a *apiProbeAccess) QueryProbes(ctx context.Context, query *probe.ListQuery) (*probe.QueryResultSnapshot, error) {
	request := &probe_client.ListProbesRequest{
		Filter:            query.Filter,
		FieldMask:         query.Mask,
		IncludePagingInfo: query.WithPagingInfo,
	}
	if query.Pager != nil {
		request.PageSize = int32(query.Pager.Limit)
		request.OrderBy = query.Pager.OrderBy
		request.PageToken = query.Pager.Cursor
	}
	resp, err := a.client.ListProbes(ctx, request)
	if err != nil {
		return nil, err
	}
	return &probe.QueryResultSnapshot{
		Probes:            resp.Probes,
		NextPageCursor:    resp.NextPageToken,
		PrevPageCursor:    resp.PrevPageToken,
		TotalResultsCount: resp.TotalResultsCount,
		CurrentOffset:     resp.CurrentOffset,
	}, nil
}

func (a *apiProbeAccess) SearchProbes(ctx context.Context, query *probe.SearchQuery) (*probe.QueryResultSnapshot, error) {
	request := &probe_client.SearchProbesRequest{
		Phrase:    query.Phrase,
		Filter:    query.Filter,
		FieldMask: query.Mask,
	}
	if query.Pager != nil {
		request.PageSize = int32(query.Pager.Limit)
		request.OrderBy = query.Pager.OrderBy
		request.PageToken = query.Pager.Cursor
	}
	resp, err := a.client.SearchProbes(ctx, request)
	if err != nil {
		return nil, err
	}
	return &probe.QueryResultSnapshot{
		Probes:            resp.Probes,
		NextPageCursor:    resp.NextPageToken,
		PrevPageCursor:    resp.PrevPageToken,
		CurrentOffset:     resp.CurrentOffset,
		TotalResultsCount: resp.TotalResultsCount,
	}, nil
}

func (a *apiProbeAccess) WatchProbe(ctx context.Context, query *probe.GetQuery, observerCb func(*probe.ProbeChange) error) error {
	request := &probe_client.WatchProbeRequest{
		Name:      query.Reference,
		FieldMask: query.Mask,
	}
	changesStream, initErr := a.client.WatchProbe(ctx, request)
	if initErr != nil {
		return initErr
	}
	for {
		resp, err := changesStream.Recv()
		if err != nil {
			return fmt.Errorf("watch recv error: %w", err)
		}
		change := resp.GetChange()
		if err := observerCb(change); err != nil {
			return err
		}
	}
}

func (a *apiProbeAccess) WatchProbes(ctx context.Context, query *probe.WatchQuery, observerCb func(*probe.QueryResultChange) error) error {
	request := &probe_client.WatchProbesRequest{
		Filter:       query.Filter,
		FieldMask:    query.Mask,
		MaxChunkSize: int32(query.ChunkSize),
		Type:         query.WatchType,
		ResumeToken:  query.ResumeToken,
	}
	if query.Pager != nil {
		request.OrderBy = query.Pager.OrderBy
		request.PageSize = int32(query.Pager.Limit)
		request.PageToken = query.Pager.Cursor
	}
	changesStream, initErr := a.client.WatchProbes(ctx, request)
	if initErr != nil {
		return initErr
	}
	for {
		respChange, err := changesStream.Recv()
		if err != nil {
			return fmt.Errorf("watch recv error: %w", err)
		}
		changesWithPaging := &probe.QueryResultChange{
			Changes:      respChange.ProbeChanges,
			IsCurrent:    respChange.IsCurrent,
			IsHardReset:  respChange.IsHardReset,
			IsSoftReset:  respChange.IsSoftReset,
			ResumeToken:  respChange.ResumeToken,
			SnapshotSize: respChange.SnapshotSize,
		}
		if respChange.PageTokenChange != nil {
			changesWithPaging.PrevPageCursor = respChange.PageTokenChange.PrevPageToken
			changesWithPaging.NextPageCursor = respChange.PageTokenChange.NextPageToken
		}
		if err := observerCb(changesWithPaging); err != nil {
			return err
		}
	}
}

func (a *apiProbeAccess) SaveProbe(ctx context.Context, res *probe.Probe, opts ...gotenresource.SaveOption) error {
	saveOpts := gotenresource.MakeSaveOptions(opts)
	previousRes := saveOpts.GetPreviousResource()

	if previousRes == nil && !saveOpts.OnlyUpdate() && !saveOpts.OnlyCreate() {
		var err error
		previousRes, err = a.GetProbe(ctx, &probe.GetQuery{Reference: res.Name.AsReference()})
		if err != nil {
			if statusErr, ok := status.FromError(err); !ok || statusErr.Code() != codes.NotFound {
				return err
			}
		}
	}

	if saveOpts.OnlyUpdate() || previousRes != nil {
		updateRequest := &probe_client.UpdateProbeRequest{
			Probe: res,
		}
		if updateMask := saveOpts.GetUpdateMask(); updateMask != nil {
			updateRequest.UpdateMask = updateMask.(*probe.Probe_FieldMask)
		}
		if mask, conditionalState := saveOpts.GetCAS(); mask != nil && conditionalState != nil {
			updateRequest.Cas = &probe_client.UpdateProbeRequest_CAS{
				ConditionalState: conditionalState.(*probe.Probe),
				FieldMask:        mask.(*probe.Probe_FieldMask),
			}
		}
		_, err := a.client.UpdateProbe(ctx, updateRequest)
		if err != nil {
			return err
		}
		return nil
	} else {
		createRequest := &probe_client.CreateProbeRequest{
			Probe: res,
		}
		_, err := a.client.CreateProbe(ctx, createRequest)
		if err != nil {
			return err
		}
		return nil
	}
}

func (a *apiProbeAccess) DeleteProbe(ctx context.Context, ref *probe.Reference, opts ...gotenresource.DeleteOption) error {
	request := &probe_client.DeleteProbeRequest{
		Name: ref,
	}
	_, err := a.client.DeleteProbe(ctx, request)
	return err
}

func init() {
	gotenaccess.GetRegistry().RegisterApiAccessConstructor(probe.GetDescriptor(), func(cc grpc.ClientConnInterface) gotenresource.Access {
		return probe.AsAnyCastAccess(NewApiProbeAccess(probe_client.NewProbeServiceClient(cc)))
	})
}
