// Code generated by protoc-gen-goten-object
// File: watchdog/proto/v1alpha2/speed_test_custom.proto
// DO NOT EDIT!!!

package speed_test_client

// proto imports
import (
	ntt_memo "github.com/cloudwan/edgelq-sdk/common/types/memo"
	ntt_meta "github.com/cloudwan/edgelq-sdk/common/types/meta"
	devices_device "github.com/cloudwan/edgelq-sdk/devices/resources/v1alpha2/device"
	devices_project "github.com/cloudwan/edgelq-sdk/devices/resources/v1alpha2/project"
	iam_attestation_domain "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/attestation_domain"
	iam_iam_common "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/common"
	iam_condition "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/condition"
	iam_organization "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/organization"
	iam_permission "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/permission"
	iam_project "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/project"
	iam_role "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/role"
	iam_service_account "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/service_account"
	iam_user "github.com/cloudwan/edgelq-sdk/iam/resources/v1alpha2/user"
	policy "github.com/cloudwan/edgelq-sdk/meta/multi_region/proto/policy"
	syncing_meta "github.com/cloudwan/edgelq-sdk/meta/multi_region/proto/syncing_meta"
	meta_service "github.com/cloudwan/edgelq-sdk/meta/resources/v1alpha2/service"
	admin_area "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/admin_area"
	common "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/common"
	probe "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/probe"
	probe_group "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/probe_group"
	project "github.com/cloudwan/watchdog-sdk/resources/v1alpha2/project"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
)

// make sure we're using proto imports
var (
	_ = &ntt_memo.Memo{}
	_ = &ntt_meta.Meta{}
	_ = &devices_device.Device{}
	_ = &devices_project.Project{}
	_ = &iam_attestation_domain.AttestationDomain{}
	_ = &iam_iam_common.Actor{}
	_ = &iam_condition.Condition{}
	_ = &iam_organization.Organization{}
	_ = &iam_permission.Permission{}
	_ = &iam_project.Project{}
	_ = &iam_role.Role{}
	_ = &iam_service_account.ServiceAccount{}
	_ = &iam_user.User{}
	_ = &policy.Policy{}
	_ = &syncing_meta.SyncingMeta{}
	_ = &meta_service.Service{}
	_ = &duration.Duration{}
	_ = &field_mask.FieldMask{}
	_ = &timestamp.Timestamp{}
	_ = &wrappers.DoubleValue{}
	_ = &latlng.LatLng{}
	_ = &admin_area.BBox{}
	_ = &common.SoftwareVersion{}
	_ = &probe.Probe{}
	_ = &probe_group.ProbeGroup{}
	_ = &project.Project{}
)

type RunSpeedTestRequestFieldPathBuilder struct{}

func NewRunSpeedTestRequestFieldPathBuilder() RunSpeedTestRequestFieldPathBuilder {
	return RunSpeedTestRequestFieldPathBuilder{}
}
func (RunSpeedTestRequestFieldPathBuilder) Name() RunSpeedTestRequestPathSelectorName {
	return RunSpeedTestRequestPathSelectorName{}
}
func (RunSpeedTestRequestFieldPathBuilder) Direction() RunSpeedTestRequestPathSelectorDirection {
	return RunSpeedTestRequestPathSelectorDirection{}
}

type RunSpeedTestRequestPathSelectorName struct{}

func (RunSpeedTestRequestPathSelectorName) FieldPath() *RunSpeedTestRequest_FieldTerminalPath {
	return &RunSpeedTestRequest_FieldTerminalPath{selector: RunSpeedTestRequest_FieldPathSelectorName}
}

func (s RunSpeedTestRequestPathSelectorName) WithValue(value *probe.Reference) *RunSpeedTestRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestRequest_FieldTerminalPathValue)
}

func (s RunSpeedTestRequestPathSelectorName) WithArrayOfValues(values []*probe.Reference) *RunSpeedTestRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestRequest_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestRequestPathSelectorDirection struct{}

func (RunSpeedTestRequestPathSelectorDirection) FieldPath() *RunSpeedTestRequest_FieldTerminalPath {
	return &RunSpeedTestRequest_FieldTerminalPath{selector: RunSpeedTestRequest_FieldPathSelectorDirection}
}

func (s RunSpeedTestRequestPathSelectorDirection) WithValue(value SpeedTestDirection) *RunSpeedTestRequest_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestRequest_FieldTerminalPathValue)
}

func (s RunSpeedTestRequestPathSelectorDirection) WithArrayOfValues(values []SpeedTestDirection) *RunSpeedTestRequest_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestRequest_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestResponseFieldPathBuilder struct{}

func NewRunSpeedTestResponseFieldPathBuilder() RunSpeedTestResponseFieldPathBuilder {
	return RunSpeedTestResponseFieldPathBuilder{}
}
func (RunSpeedTestResponseFieldPathBuilder) Direction() RunSpeedTestResponsePathSelectorDirection {
	return RunSpeedTestResponsePathSelectorDirection{}
}
func (RunSpeedTestResponseFieldPathBuilder) SpeedMbps() RunSpeedTestResponsePathSelectorSpeedMbps {
	return RunSpeedTestResponsePathSelectorSpeedMbps{}
}
func (RunSpeedTestResponseFieldPathBuilder) ServerName() RunSpeedTestResponsePathSelectorServerName {
	return RunSpeedTestResponsePathSelectorServerName{}
}
func (RunSpeedTestResponseFieldPathBuilder) ServerIp() RunSpeedTestResponsePathSelectorServerIp {
	return RunSpeedTestResponsePathSelectorServerIp{}
}
func (RunSpeedTestResponseFieldPathBuilder) ServerLatency() RunSpeedTestResponsePathSelectorServerLatency {
	return RunSpeedTestResponsePathSelectorServerLatency{}
}
func (RunSpeedTestResponseFieldPathBuilder) ServerRetransmitPercentage() RunSpeedTestResponsePathSelectorServerRetransmitPercentage {
	return RunSpeedTestResponsePathSelectorServerRetransmitPercentage{}
}

type RunSpeedTestResponsePathSelectorDirection struct{}

func (RunSpeedTestResponsePathSelectorDirection) FieldPath() *RunSpeedTestResponse_FieldTerminalPath {
	return &RunSpeedTestResponse_FieldTerminalPath{selector: RunSpeedTestResponse_FieldPathSelectorDirection}
}

func (s RunSpeedTestResponsePathSelectorDirection) WithValue(value SpeedTestDirection) *RunSpeedTestResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestResponse_FieldTerminalPathValue)
}

func (s RunSpeedTestResponsePathSelectorDirection) WithArrayOfValues(values []SpeedTestDirection) *RunSpeedTestResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestResponse_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestResponsePathSelectorSpeedMbps struct{}

func (RunSpeedTestResponsePathSelectorSpeedMbps) FieldPath() *RunSpeedTestResponse_FieldTerminalPath {
	return &RunSpeedTestResponse_FieldTerminalPath{selector: RunSpeedTestResponse_FieldPathSelectorSpeedMbps}
}

func (s RunSpeedTestResponsePathSelectorSpeedMbps) WithValue(value float64) *RunSpeedTestResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestResponse_FieldTerminalPathValue)
}

func (s RunSpeedTestResponsePathSelectorSpeedMbps) WithArrayOfValues(values []float64) *RunSpeedTestResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestResponse_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestResponsePathSelectorServerName struct{}

func (RunSpeedTestResponsePathSelectorServerName) FieldPath() *RunSpeedTestResponse_FieldTerminalPath {
	return &RunSpeedTestResponse_FieldTerminalPath{selector: RunSpeedTestResponse_FieldPathSelectorServerName}
}

func (s RunSpeedTestResponsePathSelectorServerName) WithValue(value string) *RunSpeedTestResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestResponse_FieldTerminalPathValue)
}

func (s RunSpeedTestResponsePathSelectorServerName) WithArrayOfValues(values []string) *RunSpeedTestResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestResponse_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestResponsePathSelectorServerIp struct{}

func (RunSpeedTestResponsePathSelectorServerIp) FieldPath() *RunSpeedTestResponse_FieldTerminalPath {
	return &RunSpeedTestResponse_FieldTerminalPath{selector: RunSpeedTestResponse_FieldPathSelectorServerIp}
}

func (s RunSpeedTestResponsePathSelectorServerIp) WithValue(value string) *RunSpeedTestResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestResponse_FieldTerminalPathValue)
}

func (s RunSpeedTestResponsePathSelectorServerIp) WithArrayOfValues(values []string) *RunSpeedTestResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestResponse_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestResponsePathSelectorServerLatency struct{}

func (RunSpeedTestResponsePathSelectorServerLatency) FieldPath() *RunSpeedTestResponse_FieldTerminalPath {
	return &RunSpeedTestResponse_FieldTerminalPath{selector: RunSpeedTestResponse_FieldPathSelectorServerLatency}
}

func (s RunSpeedTestResponsePathSelectorServerLatency) WithValue(value float64) *RunSpeedTestResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestResponse_FieldTerminalPathValue)
}

func (s RunSpeedTestResponsePathSelectorServerLatency) WithArrayOfValues(values []float64) *RunSpeedTestResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestResponse_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestResponsePathSelectorServerRetransmitPercentage struct{}

func (RunSpeedTestResponsePathSelectorServerRetransmitPercentage) FieldPath() *RunSpeedTestResponse_FieldTerminalPath {
	return &RunSpeedTestResponse_FieldTerminalPath{selector: RunSpeedTestResponse_FieldPathSelectorServerRetransmitPercentage}
}

func (s RunSpeedTestResponsePathSelectorServerRetransmitPercentage) WithValue(value float64) *RunSpeedTestResponse_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestResponse_FieldTerminalPathValue)
}

func (s RunSpeedTestResponsePathSelectorServerRetransmitPercentage) WithArrayOfValues(values []float64) *RunSpeedTestResponse_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestResponse_FieldTerminalPathArrayOfValues)
}

type RunSpeedTestRequestToProbeFieldPathBuilder struct{}

func NewRunSpeedTestRequestToProbeFieldPathBuilder() RunSpeedTestRequestToProbeFieldPathBuilder {
	return RunSpeedTestRequestToProbeFieldPathBuilder{}
}
func (RunSpeedTestRequestToProbeFieldPathBuilder) Direction() RunSpeedTestRequestToProbePathSelectorDirection {
	return RunSpeedTestRequestToProbePathSelectorDirection{}
}

type RunSpeedTestRequestToProbePathSelectorDirection struct{}

func (RunSpeedTestRequestToProbePathSelectorDirection) FieldPath() *RunSpeedTestRequestToProbe_FieldTerminalPath {
	return &RunSpeedTestRequestToProbe_FieldTerminalPath{selector: RunSpeedTestRequestToProbe_FieldPathSelectorDirection}
}

func (s RunSpeedTestRequestToProbePathSelectorDirection) WithValue(value SpeedTestDirection) *RunSpeedTestRequestToProbe_FieldTerminalPathValue {
	return s.FieldPath().WithIValue(value).(*RunSpeedTestRequestToProbe_FieldTerminalPathValue)
}

func (s RunSpeedTestRequestToProbePathSelectorDirection) WithArrayOfValues(values []SpeedTestDirection) *RunSpeedTestRequestToProbe_FieldTerminalPathArrayOfValues {
	return s.FieldPath().WithIArrayOfValues(values).(*RunSpeedTestRequestToProbe_FieldTerminalPathArrayOfValues)
}
